### ISSUE TITLE
Calling 'Disconnect' Inadvertently when opening up Dialogs screen?

### ISSUE THREAD

**Issue by haarj** [QuickBlox/android-ui-kit#13]
https://github.com/QuickBlox/android-ui-kit/blob/503a5cbd5545aedd2ed18f58e1138f946de8c6ed/ui-kit/src/main/java/com/quickblox/android_ui_kit/domain/usecases/ConnectionUseCase.kt#L59

The above line is being called after I am loading Dialogs screen. We don't want to disconnect and then the UI Kit internally connect again.

**Comment by vdovbnya-qb** [comment]
Hello @haarj 

We have tested this behavior using our android-ui-kit-sample.
You can find the sample here: [android-ui-kit-sample](https://github.com/QuickBlox/quickblox-android-sdk/tree/master/android-ui-kit-sample).

Regarding the code in question:
[ConnectionUseCase.kt – Line 59](https://github.com/QuickBlox/android-ui-kit/blob/503a5cbd5545aedd2ed18f58e1138f946de8c6ed/ui-kit/src/main/java/com/quickblox/android_ui_kit/domain/usecases/ConnectionUseCase.kt#L59), we were unable to reproduce the reported behavior where this line gets triggered after loading the Dialogs screen.

This specific line is only executed in two cases, both inside the AppLifecycleManager class:

When the AppLifecycleManager class is initialized:
[AppLifecycleManager.kt – Line 32](https://github.com/QuickBlox/android-ui-kit/blob/503a5cbd5545aedd2ed18f58e1138f946de8c6ed/ui-kit/src/main/java/com/quickblox/android_ui_kit/lifecycle/AppLifecycleManager.kt#L32)
When the application goes to the background:
[AppLifecycleManager.kt – Line 62](https://github.com/QuickBlox/android-ui-kit/blob/503a5cbd5545aedd2ed18f58e1138f946de8c6ed/ui-kit/src/main/java/com/quickblox/android_ui_kit/lifecycle/AppLifecycleManager.kt#L62)

Could you check if any changes were made to the source code on your side?
We also suggest testing this behavior with our sample to ensure consistent results.

**Comment by haarj** [comment]
Ok we'll take another look and let you know. We can close this for now. Thanks.
